const GAPI_CONFIG = {
  GAPI_CLIENT_ID: "REPLACE_GAPI_CLIENT_ID",
  GAPI_API_KEY: "REPLACE_GAPI_API_KEY",
};

const GAPI_CLIENT_ID = GAPI_CONFIG.GAPI_CLIENT_ID;
const GAPI_API_KEY = GAPI_CONFIG.GAPI_API_KEY;
